### ISSUE TITLE
Maven error

### ISSUE THREAD

**Issue by cybermakoki** [Alfresco-Business-Reporting/alfresco-business-reporting#1]
Hi,

I'm trying to build this plugin and I'm getting some errors when I try to run the command "mvn install"

patricia@patricia-VirtualBox:~/install/alfresco-business-reporting-master$ mvn install
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/alfresco/maven/alfresco-sdk-parent/1.1.1/alfresco-sdk-parent-1.1.1.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.incentro.alfresco.module:org.alfresco.reporting.project:1.2.1-SNAPSHOT: Could not find artifact org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 4, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project com.incentro.alfresco.module:org.alfresco.reporting.project:1.2.1-SNAPSHOT (/home/patricia/install/alfresco-business-reporting-master/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.incentro.alfresco.module:org.alfresco.reporting.project:1.2.1-SNAPSHOT: Could not find artifact org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 4, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by Martijnvandebrug** [comment]
Hi,

We are currently doing some maintenance on the Reporting tool, I will check-in a new version within 2 hours. You can send me another message if the problem still occurs.

**Comment by Martijnvandebrug** [comment]
Or check out the development branch for now.

**Comment by cybermakoki** [comment]
Hi @Martijnvandebrug ,

thans for your quick reply, I've just tried with the development branch and I've had the same error

**Comment by Martijnvandebrug** [comment]
I forgot about our private repo's, I updatet de POM's and added the correct Repo's now.

**Comment by cybermakoki** [comment]
still having the same problem

**Comment by Martijnvandebrug** [comment]
Are you still missing the alfresco-sdk-parent-1.1.1.pom?  Because it is available in the public repo: https://artifacts.alfresco.com/nexus/#nexus-search;quick~alfresco-sdk-parent
I see you're running a Virtual machine, does it have internet acces?

**Comment by cybermakoki** [comment]
I'm also trying in  my local machine and I get the same error:

Patricias-MacBook-Air:alfresco-business-reporting-development patricia$ mvn install
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project com.incentro.alfresco.module:org.alfresco.reporting.project:1.2.1-SNAPSHOT (/Users/patricia/Downloads/alfresco-business-reporting-development/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1 in http://repository.mulesoft.org/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of mulesoft-releases has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by Martijnvandebrug** [comment]
Try removing org/alfresco/maven/1.1.1/\* from your local repository (<YOURHOMEFOLDER>/.m2)
Or running maven with the -U command

**Comment by cybermakoki** [comment]
hi @Martijnvandebrug , I've tried what you said but I'mt still getting errors:

[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/alfresco/maven/alfresco-sdk-parent/1.1.1/alfresco-sdk-parent-1.1.1.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.incentro.alfresco.module:org.alfresco.reporting.project:1.2.1-SNAPSHOT: Could not find artifact org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 5, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project com.incentro.alfresco.module:org.alfresco.reporting.project:1.2.1-SNAPSHOT (/home/patricia/install/alfresco-business-reporting-development/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.incentro.alfresco.module:org.alfresco.reporting.project:1.2.1-SNAPSHOT: Could not find artifact org.alfresco.maven:alfresco-sdk-parent:pom:1.1.1 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by cybermakoki** [comment]
it tries to download the pom.xml from https://repo.maven.apache.org/maven2/org/alfresco/maven/alfresco-sdk-parent/1.1.1/alfresco-sdk-parent-1.1.1.pom and you can see that this url throws a 404 error

By the way, I'm running the pom.xml at first level, shall I run the pom.xml for repo and share individually?

**Comment by Martijnvandebrug** [comment]
Yes you can try that, when I run maven, the alfresco-sdk-parent gets downloaded from:
https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/maven/alfresco-sdk-parent/1.1.1/alfresco-sdk-parent-1.1.1.pom

**Comment by cybermakoki** [comment]
I had to add the repositories for the pom.xml to work:

```
<repositories>
    <repository>
        <id>alfresco-public</id>
        <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
    </repository>
    <repository>
        <id>alfresco-public-snapshots</id>
        <url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
        <snapshots>
            <enabled>true</enabled>
            <updatePolicy>daily</updatePolicy>
        </snapshots>
    </repository>
</repositories>
```

I have successfully deploy the share AMP, but I'm getting the following error with the repo AMP:

patricia@patricia-VirtualBox:~/install/alfresco-business-reporting-development/repo$ mvn install
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Alfresco Business Reporting 1.2.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for pentaho-reporting-engine:pentaho-reporting-engine-classic-core:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-reporting-engine:pentaho-reporting-engine-wizard-core:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-library:libloader:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-library:libserializer:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-library:libbase:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-library:libformula:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-library:libfonts:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-library:libformat:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-library:libdocbundle:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-library:libxml:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-library:libswing:jar:5.0.1-stable is missing, no dependency information available
[WARNING] The POM for pentaho-library:librepository:jar:5.0.1-stable is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.224 s
[INFO] Finished at: 2015-07-24T11:06:12+01:00
[INFO] Final Memory: 13M/44M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.alfresco.reporting: Could not resolve dependencies for project com.incentro.alfresco.module:org.alfresco.reporting:amp:1.2.1-SNAPSHOT: The following artifacts could not be resolved: pentaho-reporting-engine:pentaho-reporting-engine-classic-core:jar:5.0.1-stable, pentaho-reporting-engine:pentaho-reporting-engine-wizard-core:jar:5.0.1-stable, pentaho-library:libloader:jar:5.0.1-stable, pentaho-library:libserializer:jar:5.0.1-stable, pentaho-library:libbase:jar:5.0.1-stable, pentaho-library:libformula:jar:5.0.1-stable, pentaho-library:libfonts:jar:5.0.1-stable, pentaho-library:libformat:jar:5.0.1-stable, pentaho-library:libdocbundle:jar:5.0.1-stable, pentaho-library:libxml:jar:5.0.1-stable, pentaho-library:libswing:jar:5.0.1-stable, pentaho-library:librepository:jar:5.0.1-stable: Failure to find pentaho-reporting-engine:pentaho-reporting-engine-classic-core:jar:5.0.1-stable in https://artifacts.alfresco.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-public has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by Martijnvandebrug** [comment]
I think you don't have the latest version from the development branch :)
also add this repository: 
        <repository>
            <id>pentaho-releases</id>
            <url>http://repository.pentaho.org/artifactory/repo/</url>
        </repository>

**Comment by Martijnvandebrug** [comment]
```
    <repository>
        <id>pentaho-releases</id>
        <url>http://repository.pentaho.org/artifactory/repo/</url>
    </repository>
```

**Comment by cybermakoki** [comment]
Hmmm I can't see that repository in the last version of the development branch... I think you forgot to update the files...

**Comment by Martijnvandebrug** [comment]
You might be right

**Comment by cybermakoki** [comment]
it works now :) time to test the addon!
