### ISSUE TITLE
Not able to trigger "execute report"

### ISSUE THREAD

**Issue by kichenin** [Alfresco-Business-Reporting/alfresco-business-reporting#7]
Hi,

Thanks for your excellent add-on. I was able to install the Beta version 1.2.0 without any issues on a Alfresco 5.1. The Cron jobs are running and populating the report database. Now my problem is that, Alfresco 5.1 does not have the explorer interface and I am not able to execute the .prpt files from share. The container level report execution are also not getting triggered.

Please let me know if there any workaround to execute the reports and create output file in share interface.

Thanks & Regards
Kichenin

**Comment by Martijnvandebrug** [comment]
Have you tried version 2.1? Version 2.1 has actions in share, so that you can execute your reports from within the share interface.

**Comment by kichenin** [comment]
Hi,

Thanks for the quick reply. Please let me know from where I can I download version 2.1 pre-built amp files ?
Do I need to build from source ?. 

Thanks & Regards
Kichenin

**Comment by Martijnvandebrug** [comment]
You will have to build them from source i'm afraid

**Comment by kichenin** [comment]
Will try to build and use version 21.
Thank you for your help.

Regards
Kichenin

**Comment by Martijnvandebrug** [comment]
No problem!

**Comment by Martijnvandebrug** [comment]
You could try these:

https://github.com/Alfresco-Business-Reporting/alfresco-business-reporting/raw/580bdeae949b7e7fd98817ac0e083f33805632df/org.alfresco.reporting.amp
https://github.com/Alfresco-Business-Reporting/alfresco-business-reporting/raw/580bdeae949b7e7fd98817ac0e083f33805632df/org.alfresco.reporting.share.amp

But they are not the most recent, but atleast you don't have to build them yourself.

**Comment by kichenin** [comment]
The amp files worked well. Now I am able to execute reports and get out put.  Actually I have noticed the amp files are available in the Repo itself which I have overlooked.
We can close this issue. 

Thanks Again

Regards
Kichenin
